import type { Metadata, Viewport } from "next";
import { Inter, Newsreader } from "next/font/google";
import "./globals.css";

// Stands in for ABC Walter Neue (Dinamo), the commercial grotesque used on
// huts.com â a neutral, functional workhorse.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

// Stands in for HW Cigars (Heavyweight), the Century-inspired calligraphic
// editorial serif on huts.com. Newsreader shares that warm editorial character
// and its `opsz` axis spans 6â72, so it holds up from 20px captions to the
// 148px footer wordmark.
const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
  display: "swap",
  axes: ["opsz"],
});

// metadataBase is required by Next 16 before any relative openGraph.images
// path â omitting it is a build error, not a warning. It is also what the
// canonical URLs on /privacy and /terms resolve against, so it has to be the
// real domain now that those pages are set to index,follow.
const siteUrl = "https://backhome.ph";

// One copy each, referenced by metadata, openGraph and twitter below. These
// were three duplicated string literals and the copies had already drifted out
// of step with the page they describe.
const SITE_TITLE = "BackHome — Find trusted senior care in Cebu from overseas";

const SITE_DESCRIPTION =
  "BackHome helps overseas Filipinos find nursing homes, assisted living and " +
  "home care in Cebu, with real prices and in-person visits. Starting in " +
  "Metro Cebu.";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  applicationName: "BackHome",
  keywords: [
    "Cebu",
    "overseas Filipinos",
    "senior care",
    "nursing homes",
    "assisted living",
    "live-in caregiver",
    "home care",
    "Philippines",
    "elderly parents",
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    // PLACEHOLDER: confirm the social handles before the site goes live. The
    // domain and the image are settled; there are no X/Twitter accounts yet,
    // which is why `site` and `creator` are absent below rather than guessed.
    type: "website",
    url: siteUrl,
    siteName: "BackHome",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    locale: "en_AU",
    // The image itself is generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
  },
};

// In Next 16 themeColor belongs on the viewport export, not on metadata.
export const viewport: Viewport = {
  themeColor: "#0c310a",
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // Browser extensions commonly stamp attributes onto <html> before React
      // hydrates. This is scoped to this element only, so mismatches inside the
      // app still surface.
      suppressHydrationWarning
      // Next 16 no longer overrides scroll-behavior on navigation; this opts
      // the anchor navigation back into smooth scrolling.
      data-scroll-behavior="smooth"
      className={`${inter.variable} ${newsreader.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-base text-bark">
        {children}
      </body>
    </html>
  );
}
