import type { Metadata, Viewport } from "next";
import { Inter, Newsreader } from "next/font/google";
import "./globals.css";

// Stands in for ABC Walter Neue (Dinamo), the commercial grotesque used on
// huts.com — a neutral, functional workhorse.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

// Stands in for HW Cigars (Heavyweight), the Century-inspired calligraphic
// editorial serif on huts.com. Newsreader shares that warm editorial character
// and its `opsz` axis spans 6–72, so it holds up from 20px captions to the
// 148px footer wordmark.
const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
  display: "swap",
  axes: ["opsz"],
});

// metadataBase is required by Next 16 before any relative openGraph.images
// path — omitting it is a build error, not a warning. It is also what the
// canonical URLs on /privacy and /terms resolve against, so it has to be the
// real domain now that those pages are set to index,follow.
const siteUrl = "https://backhome.ph";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "BackHome | Trusted Family Support in Cebu",
  description:
    "BackHome is preparing a Cebu pilot to help overseas Filipinos coordinate practical support for parents, relatives and property back home.",
  applicationName: "BackHome",
  keywords: [
    "Cebu",
    "overseas Filipinos",
    "family support",
    "OFW",
    "Philippines",
    "elderly parents",
    "property checks",
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    // PLACEHOLDER: Open Graph metadata — confirm domain, handles and image
    // before the site goes live.
    type: "website",
    url: siteUrl,
    siteName: "BackHome",
    title: "BackHome | Trusted Family Support in Cebu",
    description:
      "BackHome is preparing a Cebu pilot to help overseas Filipinos coordinate practical support for parents, relatives and property back home.",
    locale: "en_AU",
    // The image itself is generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: "BackHome | Trusted Family Support in Cebu",
    description:
      "BackHome is preparing a Cebu pilot to help overseas Filipinos coordinate practical support for parents, relatives and property back home.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

// In Next 16 themeColor belongs on the viewport export, not on metadata.
export const viewport: Viewport = {
  themeColor: "#0c310a",
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // Browser extensions commonly stamp attributes onto <html> before React
      // hydrates. This is scoped to this element only, so mismatches inside the
      // app still surface.
      suppressHydrationWarning
      // Next 16 no longer overrides scroll-behavior on navigation; this opts
      // the anchor navigation back into smooth scrolling.
      data-scroll-behavior="smooth"
      className={`${inter.variable} ${newsreader.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-base text-bark">
        {children}
      </body>
    </html>
  );
}
